
app = "quyo-caddy"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  strategy = "immediate"

[env]
  CADDY_ADDRESS = ""
  XDG_CONFIG_HOME = "/caddy-storage/config"
  XDG_DATA_HOME = "/caddy-storage/data"

[mounts]
  destination = "/caddy-storage"
  source = "caddy_storage"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80

[[services]]
  internal_port = 443
  protocol = "tcp"

  [[services.ports]]
    port = 443
