
app = "quyo-caddy"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  strategy = "immediate"

[mounts]
  destination = "/data"
  source = "caddy_data"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80

[[services]]
  internal_port = 443
  protocol = "tcp"

  [[services.ports]]
    port = 443
