[devshell]
name = "flake shell"
packages = [ "flake-env" ]


[[commands]]
command = "fortune | LANG=C cowsay | lolcat"
name = "slogan"
help = "Get your slogan."


[[commands]]
command = "hello"
name = "greet"
help = "Hello, world."
category = "flake"

[[commands]]
command = "hello --greeting='Hello, project.'"
name = "greet-project"
help = "Hello, project."
category = "flake"
