
app = "quyo-node-nest-project"
kill_signal = "SIGINT"
kill_timeout = 5

#
# immediately deploy an existing public image, there will be no build process
#
# [build]
#   image = "quyo/node-nest-project:dev"
#

[deploy]
  strategy = "immediate"

#
# for sensitive information, such as credentials or passwords, use the secrets CLI command
#
[env]
  PROJECT_ENV_LABEL = "FLY"

#
# PRO: will be delivered directly to clients, bypassing the project web server
# CON: can't set Cache-Control or any other headers on assets
#
# [[statics]]
#   guest_path = "/app/dist/frontend/public/css"
#   url_prefix = "/css"
#
# [[statics]]
#   guest_path = "/app/dist/frontend/public/ext"
#   url_prefix = "/ext"
#
# [[statics]]
#   guest_path = "/app/dist/frontend/public/img"
#   url_prefix = "/img"
#
# [[statics]]
#   guest_path = "/app/dist/frontend/public/js"
#   url_prefix = "/js"
#

[[services]]
  internal_port = 3000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "requests"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
