version: '3'
services:

  caddy:
    environment:
      - PHP_HOST=${PRJ_CONTAINER_PREFIX}php:9000
    networks:
      - internal

  caddy-php:
    container_name: ${PRJ_CONTAINER_PREFIX}php
    image: ${PRJ_IMAGE_PHP}
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    name: caddy_internal
